/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.view.employee;

import controller.ActivityListerner;
import controller.InformationListener;
import controller.NotificationListener;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.ListModel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import model.Charity;
import model.Model_message;
import view.Login;
import view.new_view;

/**
 *
 * @author Admin
 */
public class Notification extends javax.swing.JFrame {

    /**
     * Creates new form Notification
     */
    private static int count = 0;
    private NotificationListener abc = new NotificationListener();
    public Notification() {
        initComponents();
        setWidthTable();
       ShowListContentNotification();
    }
    public void setWidthTable() {

        jNotification.getTableHeader().setBackground(new Color(0, 204, 255));
        jNotification.setBackground(Color.WHITE);
        jNotification.getColumnModel().getColumn(0).setPreferredWidth(130);
        jNotification.getColumnModel().getColumn(1).setPreferredWidth(250);
        jNotification.getColumnModel().getColumn(2).setPreferredWidth(130);
        jNotification.getColumnModel().getColumn(3).setPreferredWidth(130);
        jNotification.getTableHeader().setFont(new Font("Times New Roman", Font.BOLD, 17));
        ((DefaultTableCellRenderer) jNotification.getTableHeader().getDefaultRenderer())
                .setHorizontalAlignment(JLabel.CENTER);
    }
    
    public void ShowListContentNotification() {
        NotificationListener info = new NotificationListener();
        Vector<Model_message> listContent = info.getListStaffCurent("0");
        DefaultTableModel model = (DefaultTableModel) jNotification.getModel();
        model.setRowCount(0);
        for (int i = 0; i < listContent.size(); i++) {
            model.addRow(new Object[]{
               listContent.get(i).getID_model(), listContent.get(i).getHeader(), listContent.get(i).getContent(), listContent.get(i).getDate()});
        }
        jNotification.setModel(model);
    }
    public void SortWithTime(int k) {
        NotificationListener info = new NotificationListener();
        Vector<Model_message> listContent = info.sortCurrent("0", k);
        DefaultTableModel model = (DefaultTableModel) jNotification.getModel();
        model.setRowCount(0);
        for (int i = 0; i < listContent.size(); i++) {
            model.addRow(new Object[]{
               listContent.get(i).getID_model(), listContent.get(i).getHeader(), listContent.get(i).getContent(), listContent.get(i).getDate()});
        }
        jNotification.setModel(model);
    }
    public Model_message getDataFromTable() {
        int k = jNotification.getSelectedRow();
        String ID_Choose = (String) jNotification.getModel().getValueAt(k, 0);
        Vector<Model_message> list = new Vector<Model_message>();
        list = abc.FindID(ID_Choose);
        model.Model_message s = list.get(0);
        return s;
    }
     public void See(Model_message a) {
        ViewNotificatiom b = new ViewNotificatiom(a);
//       b.setMESSAGE(a);
//       b.setID_NVQL(ID_NVQL);
        b.setVisible(true);

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jtbDESC = new view.JButtonCustom();
        jtbNoti = new javax.swing.JScrollPane();
        jNotification = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jbtMinimize = new jbuttonCustom.JButtonCustom();
        jtbMaxmize = new jbuttonCustom.JButtonCustom();
        jbtExit = new jbuttonCustom.JButtonCustom();
        jbtASC = new view.JButtonCustom();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jtbDESC.setBorder(null);
        jtbDESC.setText("Sắp xếp giảm dần theo thời gian");
        jtbDESC.setBoderColor(new java.awt.Color(255, 255, 255));
        jtbDESC.setColoOver(new java.awt.Color(255, 102, 51));
        jtbDESC.setColor(new java.awt.Color(51, 255, 153));
        jtbDESC.setColorClick(new java.awt.Color(0, 204, 255));
        jtbDESC.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jtbDESC.setRadius(40);
        jtbDESC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbDESCMouseClicked(evt);
            }
        });

        jtbNoti.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbNotiMouseClicked(evt);
            }
        });

        jNotification.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jNotification.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã Thông Báo", "Tiêu Đè", "Nội Dung", "Ngày Thông Báo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jNotification.setGridColor(new java.awt.Color(0, 204, 204));
        jNotification.setRowHeight(40);
        jNotification.setSelectionBackground(new java.awt.Color(102, 204, 255));
        jNotification.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jNotificationMouseClicked(evt);
            }
        });
        jtbNoti.setViewportView(jNotification);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("THÔNG BÁO CÔNG VIỆC");

        jbtMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/subtract_16px.png"))); // NOI18N
        jbtMinimize.setBoderColor(new java.awt.Color(255, 255, 255));
        jbtMinimize.setColoOver(new java.awt.Color(255, 102, 102));
        jbtMinimize.setColorClick(new java.awt.Color(255, 51, 0));
        jbtMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtMinimizeMouseClicked(evt);
            }
        });

        jtbMaxmize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/maximize_window_24px.png"))); // NOI18N
        jtbMaxmize.setBoderColor(new java.awt.Color(255, 255, 255));
        jtbMaxmize.setColoOver(new java.awt.Color(255, 102, 102));
        jtbMaxmize.setColorClick(new java.awt.Color(255, 51, 0));
        jtbMaxmize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbMaxmizeMouseClicked(evt);
            }
        });

        jbtExit.setText("X");
        jbtExit.setBoderColor(new java.awt.Color(255, 255, 255));
        jbtExit.setColoOver(new java.awt.Color(255, 102, 102));
        jbtExit.setColorClick(new java.awt.Color(255, 51, 0));
        jbtExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtExitMouseClicked(evt);
            }
        });

        jbtASC.setBorder(null);
        jbtASC.setText("Sắp xếp tăng dần theo thời gian");
        jbtASC.setBoderColor(new java.awt.Color(255, 255, 255));
        jbtASC.setColoOver(new java.awt.Color(255, 102, 51));
        jbtASC.setColor(new java.awt.Color(51, 255, 153));
        jbtASC.setColorClick(new java.awt.Color(0, 204, 255));
        jbtASC.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jbtASC.setRadius(40);
        jbtASC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtASCMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtbNoti, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(304, 304, 304)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                .addGap(320, 320, 320))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtbMaxmize, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtExit, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(jbtASC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(139, 139, 139)
                .addComponent(jtbDESC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(124, 124, 124))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jtbMaxmize, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtExit, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbtMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtASC, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtbDESC, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtbNoti, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(2, 2, 2))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jNotificationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jNotificationMouseClicked
       Model_message b = getDataFromTable();
        See(b);
        this.setVisible(false);
    }//GEN-LAST:event_jNotificationMouseClicked

    private void jtbNotiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbNotiMouseClicked
        
    }//GEN-LAST:event_jtbNotiMouseClicked

    private void jbtMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtMinimizeMouseClicked
        setExtendedState(JFrame.HIDE_ON_CLOSE);
    }//GEN-LAST:event_jbtMinimizeMouseClicked

    private void jtbMaxmizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbMaxmizeMouseClicked
        if (count % 2 == 0) {
            setExtendedState(JFrame.MAXIMIZED_BOTH);
        } else {
            setExtendedState(JFrame.NORMAL);
        }
        count++;
    }//GEN-LAST:event_jtbMaxmizeMouseClicked

    private void jbtExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtExitMouseClicked
        this.setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_jbtExitMouseClicked

    private void jtbDESCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbDESCMouseClicked
        SortWithTime(2);
    }//GEN-LAST:event_jtbDESCMouseClicked

    private void jbtASCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtASCMouseClicked
        SortWithTime(1);
    }//GEN-LAST:event_jbtASCMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Notification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Notification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Notification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Notification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Notification().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTable jNotification;
    private javax.swing.JPanel jPanel1;
    private view.JButtonCustom jbtASC;
    private jbuttonCustom.JButtonCustom jbtExit;
    private jbuttonCustom.JButtonCustom jbtMinimize;
    private view.JButtonCustom jtbDESC;
    private jbuttonCustom.JButtonCustom jtbMaxmize;
    private javax.swing.JScrollPane jtbNoti;
    // End of variables declaration//GEN-END:variables
}
